version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_service
    restart: always
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:9090
    container_name: django_service
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - postgres
