# Generated by Django 2.2.13 on 2020-10-31 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('associated_concepts', models.TextField(blank=True, null=True, verbose_name='Conceptos Relacionados')),
                ('difficulty', models.CharField(blank=True, choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10, null=True, verbose_name='Dificultad')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de duración')),
                ('groups', models.IntegerField(blank=True, null=True, verbose_name='Grupos')),
                ('winner_selection', models.TextField(blank=True, null=True, verbose_name='Criterio selección ganador')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
                ('purpose_teaching', models.BooleanField(default=False, verbose_name='Es para enseñar')),
                ('purpose_reinforce', models.BooleanField(default=False, verbose_name='Es para reforzar')),
                ('purpose_check', models.BooleanField(default=False, verbose_name='Es para comprobar')),
                ('purpose_social', models.BooleanField(default=False, verbose_name='Es para socializar')),
                ('attachments', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('public', models.BooleanField(default=True, verbose_name='Público')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['-id'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.CharField(choices=[('Orientación', 'Orientación'), ('Elementos persuasivos', 'Elementos persuasivos'), ('Orientación de aprendizaje', 'Orientación de aprendizaje'), ('Recompensas basadas en logros', 'Recompensas basadas en logros'), ('Logros adaptables', 'Logros adaptables'), ('Factores de diversión', 'Factores de diversión'), ('Transformador', 'Transformador'), ('Orientado al bienestar', 'Orientado al bienestar'), ('Genera investigación', 'Genera investigación'), ('Basado en el conocimiento', 'Basado en el conocimiento')], max_length=30, verbose_name='Principio')),
                ('grade', models.CharField(choices=[('Nulo', 'Nulo'), ('Medio', 'Medio'), ('Significativo', 'Significativo'), ('Alto', 'Alto'), ('Muy Alto', 'Muy Alto')], max_length=30, verbose_name='Nivel')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='meejel.Instrument', verbose_name='Instrumento')),
            ],
            options={
                'verbose_name': 'Principio',
                'verbose_name_plural': 'Principios',
                'ordering': ['-id'],
                'unique_together': {('instrument', 'principle')},
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Nombre')),
                ('component_type', models.CharField(choices=[('Roles', 'Roles'), ('Materiales', 'Materiales'), ('Pasos', 'Pasos'), ('Reglas', 'Reglas'), ('Objetivos', 'Objetivos')], max_length=20, verbose_name='Tipo')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='meejel.Instrument', verbose_name='Instrumento')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meejel.Component', verbose_name='Componente')),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='meejel.Principle', verbose_name='Principio')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-id'],
                'unique_together': {('principle', 'component')},
            },
        ),
    ]
