# Generated by Django 2.2.13 on 2024-03-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meejel', '0002_auto_20201125_1545'),
        ('meejel', '0003_createUser'),
    ]

    operations = [
    ]
